### ISSUE TITLE
SvelteKit support

### ISSUE THREAD

**Issue by didier** [webpro/knip#170]
When running `knip` on a SvelteKit project, knip marks files belonging the framework as unused. This happens for routes, hooks (src/hooks.ts) and possibly more files.

An example of knip ignoring SvelteKit routes can be seen here by running `pnpm run knip`:
https://stackblitz.com/edit/sveltejs-kit-template-default-tbvdgh?file=src%2Froutes%2Flogin%2F%2Bserver.ts

**Comment by webpro** [comment]
Yes, non-JS/TS files are not included by default. Please see https://github.com/webpro/knip/blob/main/docs/compilers.md

**Comment by didier** [comment]
Hey, appreciate the swift response. This is however not about non-JS/TS files, the files (routes) in question are +(page.)server.ts files used by SvelteKit. These aren't necessarily 'imported' in the traditional sense, but they are native to the framework and thus always in use.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.17.1. See [Release 2.17.1](https://github.com/webpro/knip/releases/tag/2.17.1) for release notes._

**Comment by webpro** [comment]
Upon closing inspection I noticed the `+server.*` pattern was not included in the Svelte entry file pattern. Thanks for reporting this, @didier.

**Comment by didier** [comment]
You’re welcome! Does this also include hooks(.server/.client).ts, app.d.ts and other SK-native files?

https://kit.svelte.dev/docs/hooks

https://kit.svelte.dev/docs/advanced-routing#matching

https://kit.svelte.dev/docs/service-workers

https://kit.svelte.dev/docs/modules#$lib

**Comment by webpro** [comment]
https://github.com/webpro/knip/tree/main/src/plugins/svelte doesn't complete, no, I'll take another look :)

**Comment by webpro** [comment]
Feel free to open a PR, btw

**Comment by didier** [comment]
I’ll have a look later to see how I can contribute as I’m on my phone right now. 

Guessing I just add patterns to the entry file in the default config?

**Comment by webpro** [comment]
No worries if it doesn't work out, just let me know. Here's two relevant links if you're up to it:

- Development pointers for this project: https://github.com/webpro/knip/blob/main/.github/DEVELOPMENT.md
- We're talking updating `PRODUCTION_ENTRY_FILE_PATTERNS` in https://github.com/webpro/knip/blob/main/src/plugins/svelte/index.ts

Contributions from people that actually use the tool or framework related to the Knip plugin are very welcome, since it can be tested on actual projects (i.e. better than fixtures).
