### ISSUE TITLE
Generate a html report

### ISSUE THREAD

**Issue by ho-dor** [webpro/knip#199]
Generate a html report for the output that is generated in terminal.

**Comment by webpro** [comment]
You can use a [custom reporter](https://github.com/webpro/knip#custom-reporters) and generate anything you need. Currently this wouldn't be high on my list and no idea what that should look like, but happy to look at PRs and/or link to reporters from Knip docs.

**Comment by voxpelli** [comment]
In some of my reporters / CLI tools I started to do a Markdown abstraction so that one could easily copy and share the output in GitHub (and of course easily render to HTML)

I shared that still somewhat rough helper collection here a while ago: https://github.com/voxpelli/markdown-or-chalk

Maybe such an approach could be interesting?

**Comment by webpro** [comment]
Closing this one in favor of #204. That one will also include the option to use an external package.
