### ISSUE TITLE
Question: Support for Workers

### ISSUE THREAD

**Issue by TkDodo** [webpro/knip#237]
Hi 👋 
Thanks for ✂️ knip, it's an awesome tool.

We're currently running into some false-positives by code that is used in a file that is only imported from an entrypoint via a worker. The structure is like this:

- entrypoint `index.ts`, imports `foo.ts`
- `foo.ts` creates a Worker with something like `new Worker(new URL('./path/to/worker.js', import.meta.url))`

then all imports that are only used inside that worker are shown as unused by knip. Just wanted to know if this is something that should generally work, or maybe that's a missing feature? If it should work already, I could try to whip up a standalone reproduction.

Thanks 🙏

**Comment by webpro** [comment]
That's a missing feature. Actually two: argument(s) of `Worker` and `URL` are not statically resolved and added as entry paths yet. Conditions apply... sounds feasible!

In the meantime you could add `./path/to/worker.js` as an `entry` file.

**Comment by TkDodo** [comment]
> In the meantime you could add ./path/to/worker.js as an entry file.

Thanks 🙏 . It's a bit complicated for us, as we generate the entry points from typescript path mappings, but yes, that would work 👍

**Comment by webpro** [comment]
Maybe you can use a dynamic `knip.ts` and somehow pull those entry points in.

**Comment by webpro** [comment]
There's a snapshot dist-tagged `newurl` available (e.g. `npm install knip@newurl`).

Need to tinker a bit more about how to move forward with this, since `import.meta.url` works differently in browsers. And there are more APIs that accept a file path. But for now I think this is a safe start: only `new URL('script.js', import.meta.url)` is picked up (not `Worker`).

Please let know how this runs in your project(s)!

**Comment by webpro** [comment]
No worries, it's a useful feature to add either way.

Any chance you could share that commit?

**Comment by TkDodo** [comment]
I will try to get you a standalone reproduction

**Comment by TkDodo** [comment]
here's the reproduction, I hope I got it right:

https://github.com/TkDodo/knip-workers

with `v2.25.2`, I'm getting:

```
Unused files (2)
packages/packageA/src/components/test-worker.ts
packages/packageA/src/components/types.ts
```

with `v0.0.0-newurl.0`, I'm getting:

```
Unused files (2)
packages/packageA/src/components/test-worker.ts
packages/packageA/src/components/types.ts

Unlisted dependencies (1)
test-worker  packages/packageA/src/pages/index.tsx
```

**Comment by webpro** [comment]
Thanks a lot for the rep(r)o, Dominik.

This makes it very clear how brittle support for the feature as requested would be:

- How to know whether the `URL` with `import.meta.url` is used in client and/or server?
- In the browser, `import.meta.url` represents the current URL, how to find the corresponding file during static analysis?
- Build steps, module resolution and framework specifics complicate things further.

In the example it would be found if `test-worker` would be `test-worker.js` and relative to the file it's referenced from (`index.tsx`). Also, in this particular case it's not clear how to resolve `test-worker` to `src/components/test-worker.ts`.

> // import.meta.url: URL in browsers, file: protocol in Node.js etc.

> Conditions apply... sounds feasible!

Perhaps weird to quote myself, but the conditions are that this would only be feasible in server environments where the target file is statically resolvable, and at this point Knip is not aware of these conditions. So with that I'm going to close this issue as "wontfix". Happy to be convinced otherwise :)

I would love to be able to have Knip automatically find such entry points, but for now I can only recommend to add such files as an `entry` path in the Knip config manually.
