### ISSUE TITLE
Flag to analyse all workspaces that depend on the one passed into `-W`, for better entrypoint analysis

### ISSUE THREAD

**Issue by me4502** [webpro/knip#249]
Not sure the best way to do this one, but basically the idea is to be able to detect what entrypoints of an internal workspace aren't used without running Knip across the entire monorepo.

Thought is the single workspace would be provided via flag, and only that workspace would have items reported, but any other workspace that depends on the passed workspace would also be included in analysis. A possible flag name could be `--traverse-upwards`, `--resolve-dependents`, `--resolve-upwards`, etc. Only directly listed dependencies (across all dev deps, prod deps, peer deps, etc) should be included, not transitive dependencies. 

In the following setup,
* `A: depends on B and C`
* `B`
* `C`

If I ran `knip -W C --include-entry-exports --traverse-upwards`, I would expect Knip to provide me a report of what is unused within workspace `C`, however I would expect its analysis to also take into account usages within `A` but not `B`. The current behaviour is that anything not internally used is reported as unused, even if it's used by other workspaces within the monorepo.

This would make it significantly more feasible to use Knip to find unused entry exports of a shared internal library, without running it across an entire monorepo.

The big caveat here is that it does depend on dependencies being setup correctly, as it would miss workspaces that forget to include the dependency. I feel this isn't too big a deal, as Knip already provides functionality to resolve these cases anyway, and it's significantly better than the current situation of no other workspaces being included.

**Comment by webpro** [comment]
Knip doesn't build that kind of dependency tree yet. Sounds like a good idea. Maybe we can steal some of the `--filter` implemention that [Turborepo](https://turbo.build/repo/docs/core-concepts/monorepos/filtering) stole from [pnpm](https://pnpm.io/filtering).

**Comment by webpro** [comment]
Released a fix under the `@graph` tag:

```
npm install knip@graph
```

I consider it basically a bugfix to the `-W` flag as you describe (no extra flags necessary).

What Knip did before, was analyzing the provided `--workspace` + all ancestor workspaces (could in theory be more than just the root workspace when using nested workspaces, which is valid).

With this fix, it includes the provided `--workspace`, its ancestors and all their combined dependencies. In practice it should do what you expect.

Needs some more testing on my end too, would be great if you could try it out :)

**Comment by webpro** [comment]
Just published another `graph` dist-tag (0.0.0-graph.2). I'm want to get it right, because this feature is essential for working with large monorepos, which are otherwise hard/slow to work with. So thanks again for bearing with me :)

After going back and forth in what I think we need, and how it could be implemented, this should version come a lot closer to what you requested initially.

Its definitely still WIP, but it now only considers direct dependents and filters out results from other workspaces. Also added a little convenience to directly see what workspaces are included when using `--debug`.

One issue that must still be fixed is that it filters out issues coming from the root workspace when using `--workspace [dir]`.

To be continued. Feel free to share any feedback or insights you might have :)

**Comment by webpro** [comment]
After a few more tests and tweaks this landed in [v2.32.3](https://github.com/webpro/knip/releases/tag/2.32.3). With that, I'm going to close this ticket, but feel free to discuss further/report bugs.
