### ISSUE TITLE
[regression] Windows produces error `RangeError: path should be a ``path.relative()``d string, but got (absolute path)`

### ISSUE THREAD

**Issue by birtles** [webpro/knip#258]
Since knip 2.24.1 `knip` fails for me on Windows with errors like:

```
C:\Users\Brian\10ten-ja-reader\node_modules\ignore\index.js:351
  throw new Ctor(message);
        ^

RangeError: path should be a `path.relative()`d string, but got "C:/Users/Brian/10ten-ja-reader/package.json"
    at throwError (C:\Users\Brian\10ten-ja-reader\node_modules\ignore\index.js:351:9)
    at checkPath (C:\Users\Brian\10ten-ja-reader\node_modules\ignore\index.js:370:12)
    at Ignore._test (C:\Users\Brian\10ten-ja-reader\node_modules\ignore\index.js:491:5)
    at Ignore.ignores (C:\Users\Brian\10ten-ja-reader\node_modules\ignore\index.js:534:17)
    at ProjectPrincipal.isGitIgnored (file:///C:/Users/Brian/10ten-ja-reader/node_modules/globby/ignore.js:51:38)
    at file:///C:/Users/Brian/10ten-ja-reader/node_modules/knip/dist/ProjectPrincipal.js:175:34
    at Set.forEach (<anonymous>)
    at ProjectPrincipal.analyzeSourceFile (file:///C:/Users/Brian/10ten-ja-reader/node_modules/knip/dist/ProjectPrincipal.js:145:16)
    at analyzeSourceFile (file:///C:/Users/Brian/10ten-ja-reader/node_modules/knip/dist/index.js:185:65)
    at file:///C:/Users/Brian/10ten-ja-reader/node_modules/knip/dist/index.js:242:17
```

Bisecting the change points to 0f02519ea594be7869818827a96084d2d474420c and simply reverting those lines causes everything to work again.

I did a little bit of debugging and it seems that these lines are causing us to end up with an absolute path inside `analyzeSourceFile` (`ProjectPrincipal.js`).

For example, in 2.24.0 our `unresolved` Set would have entries like `../../manifest.json.src` but as of 2.24.1 we get `C:\Users\Brian\10ten-ja-reader\manifest.json.src`.

From there on things go haywire. We `join()` `C:/Users/Brian/10ten-ja-reader/src/background` with `C:\Users\Brian\10ten-ja-reader\manifest.json.src` which gives `C:/Users/Brian/10ten-ja-reader/src/background` which ultimately leads to `ignore.ignores` testing the path `src/background/C:/Users/Brian/10ten-ja-reader/manifest.json.src` which seems very wrong.

I'd make up a PR but I don't quite understand what 0f02519ea594be7869818827a96084d2d474420c was fixing so I'm afraid I might regress that.

**Comment by webpro** [comment]
Kudos for getting this far into it, helps a lot!

What that specific commit was trying to fix is imports that TypeScript is initially unable te resolve. For example, `./image.svg` might be at the expected location, but because of the underlying issue #185/#206 this results in `module?.resolvedModule` being `undefined`. So in that ~hack~ "fix" there's an `existsSync` for the simple case where the file is just there (without any module resolution, paths config, omitted extensions whatsoever).

The absolute path is added to `unresolvedImports` so that inside `analyzeSourceFile` the `ts.resolveModuleName` will find it (as it's an absolute path then).

There's a `TODO` as I didn't have something yet to store it properly (it should be in `internalImports`, but don't have all necessary logic/props like a few lines up there) and remove the need to `ts.resolveModuleName` it again.

My idea was to use `node:path` (not the internal posix helpers) so that on Windows that `ts.resolveModuleName` with an absolute path would still work. Which apparently unfortunately has no test coverage (the GitHub Action runs in Windows w/ PowerShell too I believe).

So a PR is most welcome! While I also understand this might be tough to unravel and obviously this isn't a part to be proud of on my end. Perhaps just exporting `resolvedImports` next to `unresolvedImports` and `unresolvedImports` from `getImportsAndExports` could be a fix.

Adding a new or extending an existing fixture so that a test fail is helpful too.

Either way, thanks for bearing with me :)

**Comment by webpro** [comment]
I've opened a repro for #206 at https://github.com/webpro/knip-dts. Fixing that will also fix this issue.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.29.0. See [Release 2.29.0](https://github.com/webpro/knip/releases/tag/2.29.0) for release notes._

**Comment by birtles** [comment]
Sorry for the delay, I've been away for the past few days. Yes, that appears to have fixed it. Thank you!

**Comment by webpro** [comment]
No worries! Thanks for the feedback, glad to hear.
