### ISSUE TITLE
"Unresolved imports" reported for package.json

### ISSUE THREAD

**Issue by thomasttvo** [webpro/knip#314]
I have this in my package.json

```json
"scripts": {
    "android:install": "adb install -r android/app/build/outputs/apk/dev/debug/app-dev-debug.apk",
```

if the path above EXISTS, knip throws an error. If NOT, the rule passes.

```
Unresolved imports (1)
[some path that's omitted]/android/app/build/outputs/apk/dev/debug/app-dev-debug.apk  package.json
error Command failed with exit code 1.
```

Expected: 
- `Unresolved imports` don't get reported for `package.json`, or maybe we should add a way to skip a specific path.
- Knip probably should throw errors if the path doesn't exist? I guess I can't say for sure as I'm not sure what it means by "resolve"

**Comment by webpro** [comment]
Knip has to make an exception here, because the default behavior of many Node.js programs is to reserve `--require` (or `-r`) for local or external "includes". Your example would resolve to the `android` package name if that file is not there.

Starting from Knip v2.38.4, you may still get back the `bin:adb` binary, but you can ignore that using `ignoreBinaries: ['adb']`.
