### ISSUE TITLE
Cache behavior with ignore list

### ISSUE THREAD

**Issue by eppisapiafsl** [webpro/knip#371]
Hi Knip team/community! 

Recently upgrade to 3.20.0 and notice a cache behavior in Knip evaluation.

### Short history/context

I run the following knip command, with a config that ignore some files with unused `enumMember`

```
knip --config knip.unused-code.json --include enumMembers --include files --no-gitignore
```

My goal was to use the ignore list from the `knip.unused-code.json` as a TODO list to gradually fix the issues

Some team mates remove a few entries from the ignore list without fixing the issues but Knip didn't complain until I upgrade to 3.20.0 😅 

### Question

Do Knip implement cache process to speed up the result?

**Comment by webpro** [comment]
No, there's no such thing as a cache between runs.

**Comment by eppisapiafsl** [comment]
🤔 I thought that was the case

Is there a better way to ignore explicit `enum` issues? I tried with `@public` but doesn't seem to work with the Enum values

A bit more of context of the behavior, I have issue in these 5 files. 
If I just remove `"src/modules/types/state.ts",` , Knip doesn't report any issue
But if I do remove the 5 of them, it does 

```
{
  "entry": ["src/index.tsx"],
  "project": ["src/**/*"],
  "ignore": [
    ....
    "src/modules/types/state.ts",
    "src/modules/types/transition.ts",
    "src/modules/types/Requirement.ts",
    "src/modules/Support.ts",
    "src/modules/interfaces.ts"
  ]
}
```

**Comment by webpro** [comment]
I think I would need a clear repro of what you want.

You should be able to tag individual `enum` members `@public`. Otherwise there might be a bug.

I need to improve the docs about `ignore`, since that adds ignore items to the glob patterns, but does not necessarily exclude the file from the reported issues (could still be included through dependency graph resolution or elsewhere). Please use `--debug` and check what happens. The output is quite comprehensive.

Feel free to open a new issue(s), I might ask for a [minimal repro](https://knip.dev/guides/troubleshooting/#minimal-reproduction).

Please file individual issues separately.

**Comment by eppisapiafsl** [comment]
Thanks @webpro ; will do!

As always, appreciate your quick response 🚀 
Closing this one
