### ISSUE TITLE
Suggestion: a more explanatory name?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#38]
👋 , coming over here from https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/174. This package looks great and I'm excited for it! 🙂 

But, the name _Knip_ -while very cute and thematic per [`## Knip?!`](https://github.com/webpro/knip/tree/60399b39508840f609dd51a8d728ee6894be666e#knip)- gives no indication to non-Dutch-speakers what the project does. Which makes it harder for developers new to the ecosystem to keep track of what packages all do. Confusing project names is a problem for all levels of developers -I personally have a hard time keeping track of everything- and is especially troublesome for early/novice developers.

Could this project please be renamed to something that won't add another word-to-memorize for folks? Just throwing out some first thoughts, maybe... `cleanall`? `find-unused-everything`? `megaprune`? `package-prune`?

**Comment by webpro** [comment]
Thanks for chiming! Really appreciate the shout out and suggestion.

The thing is, I think the opposite is just as worse: having multiple packages with a similar name do almost the same thing. Then we have to memorize which one exactly it was.

Also, this project started out as [exportman](https://www.npmjs.com/package/exportman), but that didn't fit the bill anymore after I added "unused dependencies" to the list of features. I also have a longer-term desire to add a `--fix` feature, and only then would something like "prune" (or "knip' for that matter) _really_ make sense. Anyway, I did think about this before and that's why I went with something more abstract/weird :)
