### ISSUE TITLE
How do I use Knip with Nuxt / Vue?

### ISSUE THREAD

**Issue by matthew-dean** [webpro/knip#384]
I'm sort of confused as a lot of the documentation implies that Knip just works automatically, but I cannot see how one configures for environments like Nuxt / Vue, or with `.vue` based entry points. If I run `npx knip`, essentially I get a list of all `.ts` / `.js` files in my project as unused.

**Comment by webpro** [comment]
I get that this isn't in the regular flow of the docs, but did you see https://knip.dev/features/compilers/?

If not, maybe I could ask for your feedback: at what point in the docs would you think it makes sense to start talking about this?

**Comment by webpro** [comment]
> No I didn't see it. In my mind, this is more of a "setup" task, and "features" is to me more like a "optional sweetener?" That is, being able to scan files is definitely step 1, really a part of configuration. "Features" to me is like: "Do you want nicer reporting?"

Those are great points. Personally I would think something like "monorepo" and indeed "compilers" should be closer to the configuration section. Although it also kinda depends on where you're coming from, if it's "just TypeScript" you don't need to worry about any of that.

> Also, I get that this is "compiling" in a sense, but because this is not actually creating a working build, and merely scanning, I would see it more as a "transpiling" or transpilation task.

Yeah, I was in doubt with that. The hacky regexes on that page are nowhere near compilation/transpilation/whatever, but the idea is that Knip users put the compiler of their framework when possible for best results. Those are usually called compilers.

> Finally, the Vue section would imply to me as a Vue user that Knip doesn't yet have Vue support? The reason being that simply transpiling a `.vue` file gets you closer, but there's a lot with module resolution that has to do with your Vite setup (and in this case, your Nuxt setup, which leverages Vite), and a lot of module resolution in a TypeScript environment is dependent on properly understanding `tsconfig.json` and `jsconfig.json` files (which can extend other files).

Happy to hear any feedback or bugs you may encounter!

> Btw, that perception (that Knip doesn't support Vue) could be wrong! I'm just giving you my feedback of my honest reaction based on seeing that page, that the Vue / Vite / TypeScript system isn't well-understood OR maybe better-stated, that understanding is not reflected IMO in the documentation.

There is indeed no deep/intrinsic "Vue support", since Knip is more of a general-purpose solution, and so far so good. Of course things can and should be improved, it's only early days and I'm still figuring out and observing how people are using it.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.6.1. See [Release 3.6.1](https://github.com/webpro/knip/releases/tag/3.6.1) for release notes._
