### ISSUE TITLE
Offer programmatic API

### ISSUE THREAD

**Issue by webpro** [webpro/knip#41]
The `main` function in `src/index.ts` or something similar/new could be exposed for programmatic usage. Yet needs attention in terms of API: what should it look like for external usage?

**Comment by Jym77** [comment]
Adding my 2 cents here:
knip seems to be doing a very good job at building the dependency graph of the project.
One other of my tooling problem is to generate human readable (dot, convertible to images) dependency graphs for my workspaces. So far I haven't found a tool which is doing it exactly the way I'd like…

Quoting knip's README:
> When building a dependency graph of the project, an abstract syntax tree for each file, and traversing all of this, why not collect the various issues in one go?

Would it also be possible to have a programmatic hook into that graph to use it for other purposes? I'd rather have a single tool build a single dependency graph and use it as source of truth for all my dependency graph needs (whether pruning unused exports or documenting code structure)…

**Comment by webpro** [comment]
Not in scope, closing this for now.

**Comment by webpro** [comment]
Thanks @mathieucaroff!

A great example is this GitHub Action: https://github.com/marketplace/actions/knip-reporter

> They really should have been called _post-processors_.

A bit off-topic, but I guess it depends on how you look at it:

```
knip produces results/data → processor(s) → reporter(s)
```

The initial idea was that it's processing the data before reporting it. But yeah, one can definitely argue it's processing data after it's assembled.

**Comment by rmunch** [comment]
@webpro I'm getting in touch because I'm interested in programmatic access to Knip's graph generation functionality. I'm curious if there's interest, and whether I can contibute resources to make it happen.

I'm currently using Madge in addition to Knip to generate a graph for other purposes, and would love to be able to consolidate on a single tool. Here's a summary of the challenges I'm hoping to solve:

* I've found that Madge (along with precinct and file cabinet) have significant extensibility limitations that have required patching to get the functionality I'm looking for - for example, supporting custom file types, fixing bugs with outdated parsers, etc. Knip, on the other hand, has been a joy to extend.
* It would be ideal to reuse the same graph in all cases to avoid having to maintain two implementations and to avoid duplicate processing.
* Madge doesn't support any kind of graph node metadata. As I understand it, Knip maintains a metadata object for each graph node that can capture details about each dependency. I'd love to be able to access and extend this system for my own purposes. For example, I need to know if a dependency is a type import, along with a few other cases.

Thank you very much!

**Comment by webpro** [comment]
Thank you, @rmunch.

With regards to the module graph:

- For internal usage it's proven useful, for external usage we can't really know yet—we'd need a few projects interested in this and e.g. some testing before exposing such API surface area.
- To see what's actually in there for any codebase, you could [inspect](https://github.com/webpro-nl/knip/blob/b63f5b6300522bf44dc85c589a51300a067a6eed/packages/knip/src/util/debug.ts#L16) the [graph](https://github.com/webpro-nl/knip/blob/b63f5b6300522bf44dc85c589a51300a067a6eed/packages/knip/src/index.ts#L93) and see where we're currently at
- Type definitions: https://github.com/webpro-nl/knip/blob/main/packages/knip/src/types/module-graph.ts
- Related: https://github.com/webpro-nl/knip/issues/882

[Ongoing sponsorships](https://knip.dev/sponsors) are the best way to show support for further development and future maintenance of features like this. It seems fairly high on the list of requests afaic.
