### ISSUE TITLE
Suggestion: support finding references in MDX

### ISSUE THREAD

**Issue by justingrant** [webpro/knip#494]
It's be great if knip supported [.mdx](https://mdxjs.com/) files which are used by [Storybook](https://storybook.js.org/docs/writing-docs/autodocs#with-mdx) and other documentation generators. In our project, there are a few internal-facing exports that are referenced only in our docs but don't (currently) have runtime code accessing them. 

A good example of this is a color palette, where we export categories of colors (`reds`, `greens`, etc.) so our dev docs can show a well-arranged palette page in the docs for our team members to choose from. But no actual code in our project imports `greens`. Instead, we import individual colors. But `greens` is not an unused export, because it's used by our docs.

Other than for documentation, AFAIK MDX is also sometimes used more generally as a low-cost way to generate mostly-static content.

**Comment by webpro** [comment]
There's a built-in compiler for MDX files, but it's currently limited to being auto-enabled only if `@mdx-js/mdx` or `astro` is in the list of dependencies ([source code](https://github.com/webpro/knip/blob/main/packages/knip/src/compilers/mdx.ts)).

I guess we can add a dependency to the list of "enablers" here. What should that be? Some Storybook plugin?

To enable it today (without waiting for a fix in v4). In Knip v3, this was how you had to add it explicitly, and this should still work in v4:

https://knip.dev/v3/features/compilers#mdx

You can use any MDX compiler instead of the suggested one in the example (or even a regex like the other examples on the same page). Or copy the regex from Knip source code.

**Comment by adufr** [comment]
It looks like Storybook supports MDX without the need of any subpackage, so the dependency to add could just be `storybook`.

**Comment by webpro** [comment]
Going to close this one:

- the `mdx` compiler is auto-activated if `@mdx-js/mdx` or `astro` is listed
- [Writing stories directly in MDX was removed in Storybook 8](https://storybook.js.org/docs/writing-docs/mdx)

There's still the option to use different/custom compiler.

**Comment by cylewaitforit** [comment]
@webpro Writing stories in MDX was removed but writing docs for you storybooks in MDX is very much still in place.

**Comment by webpro** [comment]
Currently the mdx compiler has only two "enablers": `@mdx-js/mdx` and `astro` (https://github.com/webpro-nl/knip/blob/main/packages/knip/src/compilers/mdx.ts). Please open a pull request if you think that list should be extended, so more users can benefit.

The manual option is to add the one from your project: https://knip.dev/features/compilers

Not familiar with any context/project, so here's a pseudo example (can be sync or async function):

```ts
import { compile } from 'lib-that-has-the-mdx-compiler';

export default {
  mdx: (text: string, filePath: string) => compile(text)
}
```

**Comment by CHC383** [comment]
@webpro 

I figured out a way to manually enable the built-in MDX compiler:
```typescript
// knip.config.ts
import mdx from 'knip/dist/compilers/mdx';

const config: KnipConfig = {
  // Manually enable built-in MDX compiler
  compilers: {
    mdx: mdx.compiler,
  },
};
```

Also created https://github.com/webpro-nl/knip/pull/875 to update the doc and the dependency list

**Comment by webpro** [comment]
> I figured out a way to manually enable the built-in MDX compiler:

Ha cool hack, let's get rid of it with the next release, really appreciate your PR!
