### ISSUE TITLE
lint-staged reported as unused with husky 9 after install

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#495]
Forwarding from https://github.com/JoshuaKGoldberg/create-typescript-app/issues/1291:

```shell
gh repo clone JoshuaKGoldberg/create-typescript-app
cd create-typescript-app

pnpm i
pnpm lint:knip # No issues detected ✅

pnpx husky install
pnpm lint:knip # lint-staged is unused? ❌
```

The full output from that second Knip run is:

```plaintext
Analyzing workspace ....
Unused devDependencies (1)
lint-staged  package.json
 ELIFECYCLE  Command failed with exit code 1.
```

I'm a little stumped here 😕. I haven't had time to debug deep into Knip, sorry.

**Comment by risu729** [comment]
I also faced this issue.

The cause is `getGitHooksPath` that calls `git config --get core.hooksPath`.
The command's result used to be `.husky` in v8 but is now `.husky/_` in v9.

This is because husky used to register hooks in `.husky/` directly, but it now registers hooks in `.husky/_/` and calls hooks in `.husky/` from them.
I guess the change is to resolve the permission issue in Windows. ([Release Note](https://github.com/typicode/husky/releases/tag/v9.0.1))

https://github.com/webpro/knip/blob/a369c402a33e6c639c72423aa5e340c041815358/packages/knip/src/util/git.ts#L12-L18

I think we can resolve this issue by not looking for `core.hooksPath` but using `.husky/` as the directory.

**Comment by justintoman** [comment]
I created what I believe is a minimal reproduction here https://github.com/justintoman/knip-lint-staged

**Comment by voxpelli** [comment]
Made a follow up to improve compatibility: https://github.com/webpro/knip/pull/537 Would love some extra eyes and tests on that
