### ISSUE TITLE
npm packages typed via `*.d.ts` reported as unused

### ISSUE THREAD

**Issue by EvgenyOrekhov** [webpro/knip#504]
## Steps to reproduce

1. Install [is-subset](https://www.npmjs.com/package/is-subset) package which doesn't have types
2. Add `src/is-subset.d.ts` file with the following contents

   ```ts
   declare module 'is-subset' {
     export default function isSubset(
       superset: Record<string, unknown>,
       subset: Record<string, unknown>,
     ): boolean;
   }
   ```

3. Add this code to the entry point

   ```ts
   import isSubset from 'is-subset';
   isSubset({}, {});
   ```

## Expected

No warnings from Knip.

## Actual

```text
Unused dependencies (1)
is-subset  package.json
```

**Comment by EvgenyOrekhov** [comment]
Knip version: 4.5.0
Node.js version: 20.10.0

**Comment by litera** [comment]
I have a similar situation. I have a **.js** file and I'm using an export from it in a **.ts** file. When I use the imported function I get typescript errors related to types. For that reason I created a **.d.ts** that only defines types for the exports in the **.js** file so I don't have any typescript errors any more.
But... Now **knip** comlpains about the **.js** file not being used. IMO this is a bug, because **knip** should assume, that **.d.ts** files don't contain any implementation, but rather only definitions.

**Comment by litera** [comment]
Seems a PR is in the works for this:
https://github.com/webpro/knip/pull/503

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.1.3-canary.0. See [Release 5.1.3-canary.0](https://github.com/webpro/knip/releases/tag/5.1.3-canary.0) for release notes._

**Comment by webpro** [comment]
Would be great if you could try out this version before I'll release v5.1.3 (I'm not in a hurry btw)

**Comment by EvgenyOrekhov** [comment]
@webpro 5.1.3-canary.0 didn't fix it for me :(

**Comment by webpro** [comment]
It does for me, although I did add an (empty) `tsconfig.json` to your example.

**Comment by EvgenyOrekhov** [comment]
In my actual project I have this in my `tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["./"]
}
```

**Comment by EvgenyOrekhov** [comment]
@webpro This regressed in a recent version (tested on 5.39.2).
