### ISSUE TITLE
The source code produces unwanted side effects

### ISSUE THREAD

**Issue by BioPhoton** [webpro/knip#551]
### Problem

Knip is a great too to track my dependencies and keep it cleen! 
I want to use the `main` function in my project to programatically run knip. 

However knip prodcues a side effect and always fetches the parameter from the current process.

**The following files produces the side effect:**
- [`cli-arguments.ts`](https://github.com/webpro/knip/blob/dc9989840f74383b0329593dc78957f66bb6e6fd/packages/knip/src/util/cli-arguments.ts#L51)

**The following files import this file:**

<img width="631" alt="Screenshot 2024-03-15 at 23 23 53" src="https://github.com/webpro/knip/assets/10064416/c6015af2-1bf9-44f5-a972-fbb75eb7167f">

### Solution

Restructure the source code in a way argument parsing ins only executed once in the `cli.ts` file. 

I suggest 3 parts, `models`, `core`, `cli` to encapsulate a specific responsibility:   

1. `model` - maintain types and argument parser as well as zod etc for the logic in `core`.  
2. `core` - main logic for programmatic reuse.   
3. `cli` - reuses `model` and maintains all validations and parsing logic for less strict types. It executes the `core` logic.

```mermaid
flowchart LR

Model
Core --> Model
Cli --> Model
Cli --> Core
```

**Comment by webpro** [comment]
At this point using Knip programmatically is not (officially) supported.

Even if setting that up properly might be trivial, it will also increase the surface level of things I'll have to support and maintain, etc. That's why I also don't ask for a PR. Opening up the plugin API to implement and use custom/external plugins is a similar issue I'd rather not introduce at this point.

Thanks for your suggestions though, they might be useful in the future.

**Comment by BioPhoton** [comment]
Changing the code would be as u mentioned easy. And you don't even need to publicly promote it. 

I don't understand how that would increase your maintenance effort.

Anyway, I may fork and publish a patch until the discussion is going forward.

Thanks for your answer and elaboration.
