### ISSUE TITLE
Comments about documentation

### ISSUE THREAD

**Issue by jfmengels** [webpro/knip#583]
I was browsing the documentation for the project, and while doing so I wrote down a number of notes and suggestions that I thought I'd share, mostly about the documentation itself but some around the tool itself. Feel free to do handle the feedback however you want and to close the issue when you see fit.

For context, I read the documentation on mobile, and followed the pages in the order by following the link to the "next chapter" every time. I hadn't seen the table of contents that is obvious on desktop. Also, I may have skipped some files (some on purpose, some not), I'll comment again elsewhere if I find things in other parts of the docs later.

This is on the long side, so have a good read!

---

https://knip.dev/overview/configuration

Should the defaults not have `!` by default to mark them as production files? (Maybe that's what you meant with a "simplified" version of the defaults?)

> Getting lots of output? Find out how to [handle issues](https://knip.dev/guides/handling-issues).

Suggestion: Change this to "Getting lots of output or false positives? Find out how to [handle issues](https://knip.dev/guides/handling-issues)."

---

https://knip.dev/explanations/entry-files

I think you should talk about `!` used for production mode already, as you should probably push people towards using the production mode feature.

Maybe say something like:
We aim for no configuration, but sometimes we will need some help in order to not report incorrect things. Here's how to...

> Knip respects .gitignore files and the ignore config option to prevent matching files from being added as entry file.

Maybe mention that this is the default behavior, that can be overridden by `--no-gitignore`. Also, is there a way to set the `--no-gitignore` in the Knip configuration file? If so, this would be a good place to put it. (I'll ask this question again for other CLI flags)

---

https://knip.dev/explanations/plugins

Can people build their own custom plugins without having it be integrated into Knip's codebase?

> Then the plugin will inform Knip that not its default entry patterns, but...

This sentence feels clunky or at least hard to understand for me.

I couldn't see a reference to https://knip.dev/reference/plugins, but I think there should be one.

---

https://knip.dev/explanations/why-use-knip

Thanks for the shoutout to my Safe Dead Code Removal article :smile:

You could mention that the autofix feature can help speed up maintenance.

> The documentation makes you think twice before using syntax like `@public` or `@internal` tags.

You can say something like "Instead of tool-specific annotations, you can use standardized annotations such as @public or @internal which serve as documentation as well." (with the link somewhere).

It's really nice that there are no disable comments :heart:

---

https://knip.dev/explanations/comparison-and-migration

Maybe it's worth indicating (or devising) a strategy for gradually adopting Knip while it reports issues (in large legacy codebases that can take a while for instance). Here's a strategy that worked for `elm-review` that works around temporarily suppressing errors: https://jfmengels.net/stop-the-bleed/.

---

https://knip.dev/features/production-mode

> To tell Knip what is production code, add an exclamation mark behind each pattern! that represents production code. Depending on file structure and enabled plugins, it’s possible that you don’t need to modify your configuration at all.
How can we tell whether it was fine correctly? Is there a way to check?

As I mentioned in private (but probably), I think you can get rid of this mode and do both analysises at once. For `elm-review`, the graph notices what imports are in production code and which ones aren't (through some similar configuration), and from that we can determine what is production code and what isn't.

But let's say you keep this for now, here's other feedback.

I'm not sure what the advice is here. Should you run Knip once without production mode and once in production mode, or is running it once enough?

Can the `strict` and `production` flags be specified in the configuration file? So that teams can enforce that Knip is always used in the same way for instance.

It's slightly unclear whether strict mode only be used with `--production` or whether it can work without it as well? (I feel like it is because of the word "Additionally").

Also, when you should **not** use `--strict`? What are good reasons not to use it?

Also, are there differences between what seems to be an application and what seems to be a package? Can `--production` be used for library packages for instance?

---

https://knip.dev/features/rules-and-filters

What are the default severity level (error/warn/off) for every rule? I'm assuming it's `error`.

I understand why **temporarily** turning rules off can be interesting, but when should users change something to `warn`? The advice and rationale even from the ESLint docs is not great IMO (and I advise against supporting severity levels). 

---

https://knip.dev/features/auto-fix

> Make sure to run in a VCS/Git repository so you can review and undo changes if necessary.

This should be general advice, not only while the feature is experimental. Sometimes an export will be reported as unused because the user forgot to use it, not because its last use was removed. In this case, the removal of the export is the wrong fix (but a good default one still).

For removed dependencies, I don't know if you already do this, but you could in the output mention that dependencies files were changed and that the user should run `npm install` or its friends.

---

https://knip.dev/features/script-parser

Related to the conversion we've had together, the docs should mention that only files that have a known extension (`.js`, `.ts`, ...) are included (and maybe indicate a way to include those with other extensions).

---

https://knip.dev/guides/commonjs

Can there be any false positives because of how CommonJS exports can be dynamic? If so, this could be worth mentioning maybe.

---

https://knip.dev/reference/cli

There is missing mentions of the fix flags.

---

https://knip.dev/reference/configuration

Don't sort options alphabetically. `projects` and `entry` are the most important ones, they should be first, then the most useful flags, but group related things together. Tell a story rather than help people find what they want (they have the search feature on the website and Ctrl-F if needed). Maybe keep things alphabetically sorted in the table of contents on the right (unless you think that is confusing). You already do this well in "Cli Arguments".

The Types section can probably be removed since it's in the linked https://knip.dev/reference/dynamic-configuration chapter anyway.

> `exclude` & `include` & `rules`

You should show an example. Just linking to another page (which doesn't always contain in-configuration examples) is not super helpful in this case.

Group these two together as well.

> `ignoreBinaries`

Maybe show an example of an in-string regular expression? This is nicely done for `ignoreDependencies` (even with a dynamic example), but I would either do it for the first one, or for all of them, or link to a section where that is explained.

> `ignoreExportsUsedInFile`

Is this an all or nothing option? It feels like something you should be able to set on a file-by-file basis (or as an Array of globs).

> `paths` &`plugins` (and maybe others)

Configuration settings like these that help the tool understand a project are pretty important for the tool to run well. In the naming scheme of "essential complexity and accidental complexity", I call these settings "accidental configuration". All the other ones are essential configuration because they allow the user to tell the tool what they want.
(more info: https://youtu.be/XjwJeHRa53A?t=1451)

Point is: I would mention all accidental configuration settings as well in the "Handling issues"/"Troubleshooting" chapters. I know Knip tries its best to get these right (and that's really awesome) and that the user should not use these unless necessary, but I think they're hidden in the wrong location for when the user is trying to figure out a false positive.

> `includeEntryExports`

This should probably be the default, no?
But each file should probably be understood differently. If an entry point is an executable file, then unused exports should all be reported. If an entry point is a file used by plugin X through the export Y, then all other exports should be reported.

---

https://knip.dev/reference/dynamic-configuration

You can apparently also use a JS file, should be mentioned in the first sentence.

> For special cases you can export an async function:

Do you have an example if what a special case is? When should people reach for this?

---

https://knip.dev/reference/issue-types

I feel like this should be mentioned earlier in the docs, probably before `Rules & Filters`. Maybe the whole "Reference" section should be moved before "Guides" at the very least, but I think it could somewhat be merged with "Features", I'm not sure why there is a split.

I feel like the rules merit examples (maybe collapsed by default?)

No unused variables, members, fields, ...?

Since Knip only focuses on unused exports+files+dependencies, I feel like it would be worth giving some advice on detecting the rest of the unused code (variables, functions, etc.), to potentially get a snowball effect (ex: unused function leads to an unused import which leads to a file being unused). Maybe worth linking to the ESLint docs for instance. Not sure this is worth having in **this** page, but I'd say it's worth having somewhere (until the day Knip chooses to do so itself?).

---

https://knip.dev/reference/jsdoc-tsdoc-tags

Similarly to before, don't sort these alphabetically. Here `@beta` references `@public` before that one appears which is not very helpful. You should therefore put `@public` first. `@public` and `@internal` are the most likely to be used, so they should be put first, etc.

Really great that you're using standards that serve as documentation to control what gets reported, instead of disable comments.
When would you recommend to use arbitrary tags? Can they be set using the configuration file? Would you ever do `--tags=-beta` for instance?

---

> https://knip.dev/reference/known-issues

I feel like this should be closer to some of the guides, notably "Troubleshooting" and "Handling issues". I think there could be a whole section around troubleshooting.

---

Is there any advice anywhere on using Knip in CI?

---

I hope this was helpful! :heart:

**Comment by webpro** [comment]
Thanks a lot for the extensive review! In e64e6ad777af2828896b6f115cb92796520a54f8 I've addressed some low-hanging fruit, this is also published to production.

I'll sort out some remaining points and address those as well soon.

Great articles and great talk, btw!

**Comment by webpro** [comment]
This morning I took the time to go over all the issues raised, trying to address them all, since they're all great bits of feedback and advice!

> https://knip.dev/overview/configuration
> 
> Should the defaults not have `!` by default to mark them as production files? (Maybe that's what you meant with a "simplified" version of the defaults?)

The defaults do have the `!` suffix, but to keep things easier to digest for newcomers they're not here in the opening ceremony yet.

> I think you should talk about `!` used for production mode already, as you should probably push people towards using the production mode feature.

I'm still on the fence about this. The default (or "dev") and production mode aren't easy to cover in a single run (not sure if that'll ever be the case), and only one can be the default mode. If I'd swap the default, my assumption is that users would miss out on more opportunities to find unused things. And starting from this default, I feel it makes sense to then add the `suffix!` to configure production mode.

On the other hand, missing out on finding unused things in production code might have more impact.

Either way, regardless of the best default, it should be super obvious the other mode exists. From both this configuration page and the entry file explainer page I'm now linking to https://knip.dev/guides/configuring-project-files where this is a main topic.
 
> > Getting lots of output? Find out how to [handle issues](https://knip.dev/guides/handling-issues).
> 
> Suggestion: Change this to "Getting lots of output or false positives? Find out how to [handle issues](https://knip.dev/guides/handling-issues)."

✅ Done

> https://knip.dev/explanations/entry-files
> 
> Maybe say something like: We aim for no configuration, but sometimes we will need some help in order to not report incorrect things. Here's how to...

✅ Done

> > Knip respects .gitignore files and the ignore config option to prevent matching files from being added as entry file.
> 
> Maybe mention that this is the default behavior, that can be overridden by `--no-gitignore`.

✅ Done

> Also, is there a way to set the `--no-gitignore` in the Knip configuration file? If so, this would be a good place to put it. (I'll ask this question again for other CLI flags)

❎ No, there isn't

> https://knip.dev/explanations/plugins
> 
> Can people build their own custom plugins without having it be integrated into Knip's codebase?

✅ No, added this to the intro

> > Then the plugin will inform Knip that not its default entry patterns, but...
> 
> This sentence feels clunky or at least hard to understand for me.

✅ Improved

> I couldn't see a reference to https://knip.dev/reference/plugins, but I think there should be one.

✅ Done

> https://knip.dev/explanations/why-use-knip
> 
> Thanks for the shoutout to my Safe Dead Code Removal article 😄
> 
> You could mention that the autofix feature can help speed up maintenance.

✅ Done

> > The documentation makes you think twice before using syntax like `@public` or `@internal` tags.
> 
> You can say something like "Instead of tool-specific annotations, you can use standardized annotations such as @public or @internal which serve as documentation as well." (with the link somewhere).

✅ Improved

> It's really nice that there are no disable comments ❤️
> 
> https://knip.dev/explanations/comparison-and-migration
> 
> Maybe it's worth indicating (or devising) a strategy for gradually adopting Knip while it reports issues (in large legacy codebases that can take a while for instance). Here's a strategy that worked for `elm-review` that works around temporarily suppressing errors: https://jfmengels.net/stop-the-bleed/.

I think the comparison/migration page is a different topic compared to gradual adoption, as I believe Knip leads to less false positives than the other tools. Still, you have a valid point here that should be addressed.

Right now there's https://knip.dev/features/rules-and-filters and https://knip.dev/reference/jsdoc-tsdoc-tags

❎ The temp-suppress is a great feature, I should open an RFC for this.

> https://knip.dev/features/production-mode
> 
> > To tell Knip what is production code, add an exclamation mark behind each pattern! that represents production code. Depending on file structure and enabled plugins, it’s possible that you don’t need to modify your configuration at all.
> How can we tell whether it was fine correctly? Is there a way to check?

✅ Yes, there's `--debug` which shows what files are added and why, and what plugins are enabled and what files they add. Added a sentence to emphasize this.

> As I mentioned in private (but probably), I think you can get rid of this mode and do both analysises at once. For `elm-review`, the graph notices what imports are in production code and which ones aren't (through some similar configuration), and from that we can determine what is production code and what isn't.

❎ Yeah at this point this is not really in scope. Could be a killer feature, though.

> But let's say you keep this for now, here's other feedback.
> 
> I'm not sure what the advice is here. Should you run Knip once without production mode and once in production mode, or is running it once enough?

✅ Added some notes to this.

> Can the `strict` and `production` flags be specified in the configuration file? So that teams can enforce that Knip is always used in the same way for instance.

❎ No, there's no parity at all between CLI and config file options. Usually this should be in the `package.json#scripts#knip` anyway.

> It's slightly unclear whether strict mode only be used with `--production` or whether it can work without it as well? (I feel like it is because of the word "Additionally").

✅ Added notes to this (`--strict` implies `--production`)

> Also, when you should **not** use `--strict`? What are good reasons not to use it?

❎ When the project is not setup in a strict manner. Lots of repos have dependencies listed only in the root workspace and then use them wherever they want in descendant workspaces (e.g. typescript or eslint, etc). Or frontend repos that have no `devDependencies` because everything is compiled anyway. In other words, there's only `dependencies` while many of those would be considered `devDependencies` in the more strict sense.

> Also, are there differences between what seems to be an application and what seems to be a package? Can `--production` be used for library packages for instance?

Not sure exactly what you mean here. Can you give an example of a difference between an app and a lib that's relevant to Knip?

One thing that comes to mind is that sometimes monorepos contain shared workspaces, and for these the unused exports even in entry files should be reported. There's an option for that which can be set globally or on a per-workspace level: https://knip.dev/reference/configuration#includeentryexports

> https://knip.dev/features/rules-and-filters
> 
> What are the default severity level (error/warn/off) for every rule? I'm assuming it's `error`.

✅ The default is "error" indeed, and it's in the table.

> I understand why **temporarily** turning rules off can be interesting, but when should users change something to `warn`? The advice and rationale even from the ESLint docs is not great IMO (and I advise against supporting severity levels).

❎ Yes, I think I actually agree. Something is an error or not. Let's say warnings are the intermediate step towards the temp-suppress feature :)

> https://knip.dev/features/auto-fix
> 
> > Make sure to run in a VCS/Git repository so you can review and undo changes if necessary.
> 
> This should be general advice, not only while the feature is experimental. Sometimes an export will be reported as unused because the user forgot to use it, not because its last use was removed. In this case, the removal of the export is the wrong fix (but a good default one still).
> 
> For removed dependencies, I don't know if you already do this, but you could in the output mention that dependencies files were changed and that the user should run `npm install` or its friends.

✅ Yeah that's mentioned in http://localhost:4321/features/auto-fix#post-fix

> https://knip.dev/features/script-parser
> 
> Related to the conversion we've had together, the docs should mention that only files that have a known extension (`.js`, `.ts`, ...) are included (and maybe indicate a way to include those with other extensions).

✅ Done

> https://knip.dev/guides/commonjs
> 
> Can there be any false positives because of how CommonJS exports can be dynamic? If so, this could be worth mentioning maybe.

✅ Extended the intro a bit with this

> https://knip.dev/reference/cli
> 
> There is missing mentions of the fix flags.

✅ Done

> https://knip.dev/reference/configuration
> 
> Don't sort options alphabetically. `projects` and `entry` are the most important ones, they should be first, then the most useful flags, but group related things together. Tell a story rather than help people find what they want (they have the search feature on the website and Ctrl-F if needed). Maybe keep things alphabetically sorted in the table of contents on the right (unless you think that is confusing). You already do this well in "Cli Arguments".

✅ Agreed! Done

> The Types section can probably be removed since it's in the linked https://knip.dev/reference/dynamic-configuration chapter anyway.

❎ Not removed, but shortened.

> > `exclude` & `include` & `rules`
> 
> You should show an example. Just linking to another page (which doesn't always contain in-configuration examples) is not super helpful in this case.

❎ The linked page contains examples.

> Group these two together as well.
> 
> > `ignoreBinaries`
> 
> Maybe show an example of an in-string regular expression? This is nicely done for `ignoreDependencies` (even with a dynamic example), but I would either do it for the first one, or for all of them, or link to a section where that is explained.

✅ Done

> > `ignoreExportsUsedInFile`
> 
> Is this an all or nothing option?

❎ Yes.

> It feels like something you should be able to set on a file-by-file basis (or as an Array of globs).

❎ Maybe, it never came up before. If there's demand it'll come my way :)

> > `paths` &`plugins` (and maybe others)
> 
> Configuration settings like these that help the tool understand a project are pretty important for the tool to run well. In the naming scheme of "essential complexity and accidental complexity", I call these settings "accidental configuration". All the other ones are essential configuration because they allow the user to tell the tool what they want. (more info: https://youtu.be/XjwJeHRa53A?t=1451)
> 
> Point is: I would mention all accidental configuration settings as well in the "Handling issues"/"Troubleshooting" chapters. I know Knip tries its best to get these right (and that's really awesome) and that the user should not use these unless necessary, but I think they're hidden in the wrong location for when the user is trying to figure out a false positive.

✅ I've been refactoring and cross-linking the docs a bit also with this in mind.

> > `includeEntryExports`
> 
> This should probably be the default, no? But each file should probably be understood differently. If an entry point is an executable file, then unused exports should all be reported. If an entry point is a file used by plugin X through the export Y, then all other exports should be reported.

❎ Not sure about this: if it would be, how to get rid of the false positives? If it would be, correctness will be improved, but also means more work for both users and the maintainer of Knip. Your examples are correct. The unused "not `Y'` exports for plugin `X` isn't something I fancy maintaining, though ;)

> https://knip.dev/reference/dynamic-configuration
> 
> You can apparently also use a JS file, should be mentioned in the first sentence.

✅ OK

> > For special cases you can export an async function:
> 
> Do you have an example if what a special case is? When should people reach for this?

❎ Don't have an example at hand, but it's mostly import calls to other files.

> https://knip.dev/reference/issue-types
> 
> I feel like this should be mentioned earlier in the docs, probably before `Rules & Filters`.

❎ Not sure, the issues are reported automatically and folks can find it when they need it? It's a fairly long boring list.

> Maybe the whole "Reference" section should be moved before "Guides" at the very least, but I think it could somewhat be merged with "Features", I'm not sure why there is a split.

❎ The split comes from a slight variation of this idea: https://documentation.divio.com

> I feel like the rules merit examples (maybe collapsed by default?)
> 
> No unused variables, members, fields, ...?
> 
> Since Knip only focuses on unused exports+files+dependencies, I feel like it would be worth giving some advice on detecting the rest of the unused code (variables, functions, etc.), to potentially get a snowball effect (ex: unused function leads to an unused import which leads to a file being unused). Maybe worth linking to the ESLint docs for instance. Not sure this is worth having in **this** page, but I'd say it's worth having somewhere

✅ There are updated bits here:

- https://knip.dev/explanations/why-use-knip#greenfield-or-legacy
- https://knip.dev/features/auto-fix#post-fix

> (until the day Knip chooses to do so itself?).

❎ Knip focuses particularly on "inter-file issues", there's plenty of tools out there that do "in-file issues" such as ESLint, etc. etc. Scope is already large.

> https://knip.dev/reference/jsdoc-tsdoc-tags
> 
> Similarly to before, don't sort these alphabetically. Here `@beta` references `@public` before that one appears which is not very helpful. You should therefore put `@public` first. `@public` and `@internal` are the most likely to be used, so they should be put first, etc.

✅ Agreed! Done

> Really great that you're using standards that serve as documentation to control what gets reported, instead of disable comments. When would you recommend to use arbitrary tags?

✅ E.g. when users really want to use e.g. `@knipignore` to ignore problematic imports or exports. Ideally this would never be necessary, but also I don't want to be a burden here (e.g. when waiting for a fix in Knip). Or when they have specific areas to focus on or exclude (e.g. `-@internal`), could be anything, really.

> Can they be set using the configuration file?

❎ No.

> Would you ever do `--tags=-beta` for instance?

✅ That should work. Using `-beta` or `+beta` allows you to exclude or focus on any tag.

> > https://knip.dev/reference/known-issues
> 
> I feel like this should be closer to some of the guides, notably "Troubleshooting" and "Handling issues".

❎ It's linked from there. It's not a guide, but more of a reference.

> I think there could be a whole section around troubleshooting.

❎ I think of the main pain points of Knip is the configuration of project files, which now has a dedicated guide: https://knip.dev/guides/configuring-project-files (linked to from several locations). Hopefully this helps.

> Is there any advice anywhere on using Knip in CI?

✅ Updated with stand-out tip: https://knip.dev/explanations/why-use-knip#greenfield-or-legacy

> I hope this was helpful! ❤️

✅ ✅ ✅ It was super helpful, really appreciate the efforts put into this! Very good to re-iterate and re-think certain topics, to "sharpen the knife" at times. Lots of little and big improvements in copy that I trust many users will appreciate a lot (consciously or not). Feel free to discuss more if you'd like, but I'm going to close the issue with the next commit. Thanks again! 🙏

**Comment by jfmengels** [comment]
Awesome, I'm glad this was helpful 😊

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.10.0-canary.1. See [Release 5.10.0-canary.1](https://github.com/webpro/knip/releases/tag/5.10.0-canary.1) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._
