### ISSUE TITLE
Add a brief page to the documentation showing how to use on CI

### ISSUE THREAD

**Issue by ptmkenny** [webpro/knip#608]
The project page mentions using knip on CI, but the documentation doesn't give any specific examples.

In my case, I was introducing knip into an existing project, so I needed to make use of `--max-issues`.  I suggest adding a CI page highlighting `--max-issues` and `--no-exit-code`; since this is a headline feature of knip, it should be easy to find how to get started in the docs.

**Comment by webpro** [comment]
Thanks for raising this, I totally agree. Although these flags should not be featured as highlights, I think. Essentially they're hiding issues. Obviously in large projects issues can't be fixed at once when introducing Knip (or Knip itself reports false positives), so that's why the options do exist.

That said, this topic is mostly kind of tucked away in https://knip.dev/explanations/why-use-knip and at the very bottom of the CLI options pages. And no examples at all indeed.

There should be a "Using Knip in CI" page or similar, including examples and warnings :)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.14.0. See [Release 5.14.0](https://github.com/webpro/knip/releases/tag/5.14.0) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._
