### ISSUE TITLE
Remove `patch-package`?

### ISSUE THREAD

**Issue by voxpelli** [webpro/knip#61]
Patching dependencies that may be used by other packages doesn't feel right.

On top of that it adds a `postinstall` script that will not always run (eg. not when doing `npm install --ignore-scripts`)

You also get warnings on eg. socket.dev: https://socket.dev/npm/package/knip (disclaimer: I work for socket.dev, but I'm not opening this to promote socket.dev in any way, it's simply that I have this on for PR:s and thus get warnings for  `postinstall` script's like this

**Comment by webpro** [comment]
I'm not a fan of `postinstall` scripts myself either, but the problem is that I don't know another way of overriding the esbuild-register behavior of using the project local TypeScript config, which may have the `target: 'es5'` compiler option. Knip uses esbuild-register to have esbuild transform modules in the analyzed project, which leads to errors like this:

>  Transforming const to the configured target environment ("es5") is not supported yet

**Comment by webpro** [comment]
In knip v2 patch-package is no longer used.

**Comment by webpro** [comment]
...and no (other) `postinstall` scripts either :)
