### ISSUE TITLE
To read TypeScript configuration files Jest requires "ts-node"

### ISSUE THREAD

**Issue by marco-carvalho** [webpro/knip#620]
I have a project with a `jest.config.ts`, and `ts-node` and `jest` both installed. But `knip` shows me that `ts-node` is a `Unused devDependencies`. This is a bug or am I missing something?

https://jestjs.io/docs/configuration
> To read TypeScript configuration files Jest requires [ts-node](https://npmjs.com/package/ts-node). Make sure it is installed in your project.

**Comment by webpro** [comment]
If there's no reference to `ts-node` then Knip will report it as unused.

Knip can't assume `ts-node` is required, otherwise it would be incorrectly reported as an unlisted dependency in situations where it's not used.

But if there's a way to figure out this distinction, we can add a condition. For instance, "if the config file ends with `.ts` then `ts-node` is required".

**Comment by marco-carvalho** [comment]
https://github.com/jestjs/jest/issues/14752 related
