### ISSUE TITLE
Delete unused exports automatically 

### ISSUE THREAD

**Issue by Thibaud-43** [webpro/knip#63]
Hello!

thanks for sharing this package, it's really great!

What do you think of having a "--fix" option, a bit like Eslint does, removing the "export" token for unused export and unused export types

In our case, we have thousands of unused types in our code base, and auto-removing export would play very well with the unused variables, etc. from eslint, as we would chain them

thank you

**Comment by webpro** [comment]
That's on the roadmap, but currently I'm working on making it a lot faster and improving correctness first (v2).

**Comment by webpro** [comment]
First alpha version for `--fix` is here: https://github.com/webpro/knip/tree/feat/auto-fix-issues#auto-fix-issues

You can install and try [v2.21.0-autofix.0](https://github.com/webpro/knip/releases/tag/2.21.0-autofix.0) using e.g.:

```
npm install knip@autofix
```

Still a way to go to make it more comprehensive and solid, but the basics are there. Feel free to run it on your repositories and let me know what you think. Copied from the updated docs:

## Auto-fix Issues

**WARNING**: Experimental feature. Make sure to run in a Git repository so you can revisit and undo changes.

Use `--fix` to let Knip automatically apply fixes. Currently includes:

- Remove `export` keyword for unused exports
- Remove `export` keyword for unused types
- Remove unused `dependencies` and `devDependencies` from `package.json`

Use `--fix-type` to only fix specific type(s) of issues (`exports`, `types` and/or `dependencies`).

### Notes

- Run `npm install` after dependencies have been removed (or `yarn` or `pnpm i`).
- Run `eslint --fix` or similar after Knip removed `export` keywords, since then such tools can detect whether variables
  are unused within files.

**Comment by fb55** [comment]
That is awesome, looking forward to using it going forward!

On the code: You are using sync fs methods in an async method – seems unintentional.

**Comment by webpro** [comment]
> That is awesome, looking forward to using it going forward!

🎉 
 
> On the code: You are using sync fs methods in an async method – seems unintentional.

Good catch! It's because I want to use `PackageJson.load` (for som reason this and `fs/promises.readFile` acted funky). But left the `async` anyway to allow that later on.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.7.0. See [Release 3.7.0](https://github.com/webpro/knip/releases/tag/3.7.0) for release notes._
