### ISSUE TITLE
False positive when using a dynamic default importing

### ISSUE THREAD

**Issue by dd-jonas** [webpro/knip#648]
Repro: https://stackblitz.com/edit/vitejs-vite-rwjllt?file=src%2Findex.ts (run `npm run knip` to test)

Notice how `xlsx.ts` re-exports some properties from a library. Then, in `index.ts`, these properties are dynamically imported as `const XLSX = await import ('./xlsx');`. Knip reports these properties as unused, even though they are accessed below. Using object destructuring when dynamically importing (`const { utils, writeFile } = await import ('./xlsx');`) seems to work though.

**Comment by webpro** [comment]
The `xlsx.ts` does not have a default export, so it's an incorrect import to begin with. Named exports → named imports. So this is expected behavior from Knip.

In CommonJS this is more... _common_, but in ESM it's incorrect. An alternative is to use `import * as XLSX`, but that's not possible with dynamic imports.

**Comment by dd-jonas** [comment]
Oh I see, thanks for clearing that up @webpro!
