### ISSUE TITLE
Integrating knip with React not working

### ISSUE THREAD

**Issue by jalopez526** [webpro/knip#65]
I'm trying to run knip with a react project and I think default configuration should suffice, but somehow is saying all my used files are unused, so im not sure where to look at.

knip.json

```json
{
    "$schema": "https://unpkg.com/knip@1/schema.json",
    "entry": ["src/main.js"],
    "project": ["src/**/*.{js,jsx}"]
}
```

Project structure:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/8070933/220604607-6a38e378-4512-4ecb-af13-6b43b718a7ca.png">

Any thoughts  @webpro? Im probably doing something wrong.

**Comment by jalopez526** [comment]
It's quite big so I attach a file.
[knip.log](https://github.com/webpro/knip/files/10806311/knip.log)

Unfortunately. It's a private project that I cannot sh

are. I could probably replicate a small version but not sure if that will help.

**Comment by webpro** [comment]
I think the issue is that you are probably using import specifiers like this:

```
import React from 'react';
import App from 'components/App';
```

Although `components/App` resolves just fine to the file you expect, Knip currently files this under "unresolved dependencies", because it doesn't understand (yet) that `components` is not a package in `node_modules`.

Personally I would rather use relative paths like `./components/App` or `../components/App` for local imports.

This is usually recommended and also shown in most examples (such as at the Parcel website: https://parceljs.org/recipes/react/), so this is also the work-around I'm recommending.

Still, I'm going to label this as a bug, because Knip should not fail to recognize them as local, resolvable imports.

**Comment by webpro** [comment]
Unfortunately atm this does not seem to be an easy fix, but I will definitely try to include it in the upcoming v2. Stay tuned for updates :)

**Comment by webpro** [comment]
I made an attempt to make this work in v2. You could try this by installed the `next` version already:

```
npm install knip@next
```

**Comment by webpro** [comment]
This should work in v2, please open a new issue if there are any problems.
