### ISSUE TITLE
allow ignore values at the individual workspace level

### ISSUE THREAD

**Issue by gajus** [webpro/knip#68]
```json
{
  "workspaces": {
    "packages/*": {
      "ignore": [
        "**/*.d.ts"
      ],
      "entry": [
        "src/index.ts!"
      ],
      "project": [
        "src/**/*.ts!"
      ]
    },
    "packages/eslint-config-contra": {
      "ignoreDependencies": ["eslint-config-canonical"],
      "entry": [
        ".eslintrc.js!"
      ],
      "project": [
        ".eslintrc.js!"
      ]
    }
  }
}
```

Would expect `eslint-config-canonical` to be ignored.

However, still getting error:

```
at 14:24:28 ❯ knip --production
Unused dependencies (1)
eslint-config-canonical  packages/eslint-config-contra/package.json
```

**Comment by gajus** [comment]
Few related issues:

* adding non-existent workspace, does not throw an error, i.e. I accidentally added `packages/eslint-config-foo`, not noticing that I typed wrong name, and knip did not warn me about it.
* not clear why knip thinks that `eslint-config-canonical` is not found, despite it being used in `.eslintrc.js`.

```js
module.exports = {
  ignorePatterns: ['/dist', '**/__generated__'],
  overrides: [
    {
      extends: ['canonical/json'],
      files: '*.json',
    },
    {
      extends: ['canonical/yaml'],
      files: '*.yaml',
    },
  ],
};
```

**Comment by gajus** [comment]
Few small hiccups aside, what an AMAZING software. Thank you

**Comment by gajus** [comment]
> not clear why knip thinks that eslint-config-canonical is not found, despite it being used in .eslintrc.js.

The irony is that if I install eslint in that workspace, it stops reporting  `eslint-config-canonical` as not found, but that workspace does not use eslint. But I am guessing the plugin system is checking if package.json references eslint.

**Comment by webpro** [comment]
Thanks for all the feedback! Very much appreciated. If possible, next time, please report them separately.

> `ignoreDependencies`

This works only globally indeed. But your expectation makes sense, so I'll see what I can do :)

> adding non-existent workspace, does not throw an error

Good idea, I'll add that.

> not clear why knip thinks that `eslint-config-canonical` is not found, despite it being used in `.eslintrc.js.`

Maybe there's a bug with the form of `canonical/json`, will look into it!

> But then it fails with --production again.

This might be an odd issue, since what happens here is a mix-up of eslint as a plugin (not part of `--production`) and providing `.eslintrc.js` as a production entry file. My idea/advice would be to simply not consider this file as a production file (unless the project **is** an eslint plugin or something).

**Comment by webpro** [comment]
> But I am guessing the plugin system is checking if package.json references eslint.

Indeed. Each plugin has some minimal docs for this, e.g. https://github.com/webpro/knip/blob/main/src/plugins/eslint/README.md
