### ISSUE TITLE
Autoload Prettier plugins

### ISSUE THREAD

**Issue by ontanj** [webpro/knip#70]
According to [Prettier's documentation](https://prettier.io/docs/en/plugins.html#using-plugins), plugins are autoloaded.

> Plugins are automatically loaded if you have them installed in the same node_modules directory where prettier is located. Plugin package names must start with @prettier/plugin- or prettier-plugin- or @<scope>/prettier-plugin- to be registered.

However Knip's Prettier plugin only marks plugins mentioned in a configuration files as used.

This leads to false positives where you, because of an existing plugin, expect none.

**Comment by ontanj** [comment]
I fail to see how _use all packages listed under `plugins` in config file or under `prettier.plugins` in manifest_ is less specific than _use all packages starting with `@prettier/plugin-` or `prettier-plugin-` or `@/prettier-plugin-`_. Both are specific to Prettier and that's the whole point of the plugin.

But if you insist on keeping it this way, you should add a clear description of this issue. When using a plugin you expect it to be fully compatible, and not that you need to manually verify everything it has done.

**Comment by webpro** [comment]
It's not about how specific the rules are, they are clear. It's about the fact that this plugin would have to introduce a new concept of doing lookups on the file system by itself to find such dependencies.

It's not rocket science, but Knip already has a lot of concepts to wire together, that's why this currently has low priority in this project.

I think I was a bit too deep into a major refactoring the other day and added the "wontfix" label too quickly, sorry about that. Probably more tooling out there use similar auto-loading mechanics so let's at least keep this ticket open and see what happens.

**Comment by webpro** [comment]
Prettier v3 has removed auto-loading of plugins, so we can close this issue as well.
