### ISSUE TITLE
`peerDependencies` ignored in strict mode

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#76]
When in strict mode, `peerDependencies` should also be considered, not just `dependencies`.

**Comment by webpro** [comment]
Thanks for he report.

Although I agree, it's not an exact science. Peer dependencies indicate the "host" dependency they need, but may not be referenced anywhere in source code. With this change, this results in an unused (peer) dependency. On the other hand, without the change, peer dependencies might be referenced in code and reported as unlisted. I guess the latter is what you faced?

I'm still a bit on the fench, but this change is in the latest v2 alpha. Any chance you could try and see if it does what you expect?

Didn't implement it in v1 yet, as it might be an unexpected/breaking change. But since it's behind two flags it's likely not an issue at all.

**Comment by RebeccaStevens** [comment]
For my library [is-immutable-type](https://github.com/RebeccaStevens/is-immutable-type), I've got the following 3 peer dependencies:

```json
{
  "peerDependencies": {
    "@typescript-eslint/type-utils": ">=5.30.5",
    "@typescript-eslint/utils": ">=5.30.5",
    "typescript": ">=4.7.4"
  }
}
```

Using the command `knip --production --strict --exclude exports` (excluding exports because I'm using tree shaking when building)

With `2.0.0-alpha.6` I get:

```txt
Unlisted dependencies (4)
@typescript-eslint/type-utils  src/calculate.ts
@typescript-eslint/utils       src/calculate.ts
typescript                     src/calculate.ts
typescript                     src/utils.ts
```

With `2.0.0-alpha.7` I get:

```txt
Unused dependencies (2)
@typescript-eslint/type-utils  package.json
@typescript-eslint/utils       package.json

Unlisted dependencies (4)
@typescript-eslint/type-utils  src/calculate.ts
@typescript-eslint/utils       src/calculate.ts
typescript                     src/calculate.ts
typescript                     src/utils.ts
```

Neither of these are what I'd expect.

Obviously something's going wrong with `alpha.7` as two dependencies are listed both under unused and unlisted. All three of the marked unlisted dependencies are declared as peer dependencies, so I'd expect them not to be marked as unlisted.

**Comment by webpro** [comment]
Gotcha, didn't grasp all of that from the initial report. Thanks for pointing me to your repo, it's a nice extra test case.

Issue should be solved in v2.

**Comment by RebeccaStevens** [comment]
All working as expected now

**Comment by RebeccaStevens** [comment]
All working as expected now 🎉
