### ISSUE TITLE
Unlisted dependencies flags local files

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#77]
If I use a local file as a dependency for a plugin supported by knip, knip flags that file. knip should ignore local files when determining "Unlisted dependencies".

Example:

```jsonc
// typedoc.json
{
  "plugin": ["./dist/index.cjs"],
}
```

![image](https://user-images.githubusercontent.com/7224206/224462461-02b832dd-58b6-4d91-87b2-448db9fbe306.png)

**Comment by webpro** [comment]
Short version: that's a bug, should be fixed.

Long version: I once started out writing plugins with the idea that they are in a better position to handle this themselves for a few reasons:

- Relative specifiers from extended configs (so that they can't be resolved properly anymore somewhere else)
- Some tools have special syntax, e.g. as Jest has `<rootDir>`
- Implicit relative specifiers, as supported by TypeScript (e.g. `dir/module` where `dir` could also be a package in `node_modules)

That's also why some plugins return both `dependencies` and `entryFiles`. All of this turned out to be unnecessarily complicating this at the plugin side, so now I've refactored things and it seems to make a lot of sense to handle this centrally. Also, it should be easy and fun to write plugins without having to worry about this: just return a single array of dependencies.

I'm working on releasing this in v2 alpha now, and then backporting it to v1 as well.

**Comment by webpro** [comment]
It's in [v2.0.0-alpha.6](https://github.com/webpro/knip/releases/tag/2.0.0-alpha.6). Next step is to port it back into v1.

**Comment by RebeccaStevens** [comment]
On a sidenote: does knip currently support [package self-referencing](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name)?

**Comment by webpro** [comment]
> On a sidenote: does knip currently support [package self-referencing](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name)?

That's not something I explicitly took into account, no.

**Comment by webpro** [comment]
> and then backporting it to v1 as well.

Unfortunately, I would have to backport too many other things from v2, so for now I simply tried to fix the issue for this particular plugin. The generic fix is in v2.
