### ISSUE TITLE
Add detection for zx

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#96]
[zx](https://github.com/google/zx) is a nifty tool for writing JS scripts that call to the shell. For example, this is a file that would run `ls`:

```js
await $`ls`;
```

Knip doesn't know that packages whose CLIs are run in this way are used. For example, in https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/315, we had to add a Knip `ignoreDependencies` entry for `all-contributors-cli` only ever referenced in a script run by zx:

```js
await $`pnpm all-contributors generate`;
```

Would you accept a PR adding support for detection of `zx`? I imagine the criteria would be any script that has an <code>await $\`...\`</code>, but if that's too loose, their suggested file prefix is `#!/usr/bin/env zx`.

If so: I'd be very eager to add this in! I'd love to give back to Knip after just filing issues on it. 😄

**Comment by JoshuaKGoldberg** [comment]
I honestly hadn't look into it at all. I'm also happy to wait to add this in till the concepts are solidified. Do you know the general timeline there, and/or would be up for pinging me? I'm guessing it's in my best interest to wait 😄

**Comment by webpro** [comment]
Alright, organizing this a bit might open up more interesting use cases. Not sure when this is done, but let's leave this ticket open and I'll ping you.

**Comment by webpro** [comment]
After I got this organized, it felt a bit weird to remove the only use case I had for the new "script node visitor" so that you could implement it. My apologies about that if you looked forward to implementing it :-D

On the other hand, the good news is that this is now in [v2.2.0](https://github.com/webpro/knip/releases/tag/2.2.0), with the additional note that the visitor is only enabled in files with the `zx` shebang.

**Comment by JoshuaKGoldberg** [comment]
Haha no worries at all, thanks for implementing!

**Comment by webpro** [comment]
Cool! It was essentially 3 lines of code: https://github.com/webpro/knip/blob/main/src/typescript/visitors/scripts/zx.ts
